<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Product>OPNX.UI.WPF</Product>
    <Description>OPNX WPF UI library for VMS, NVR, and real-time monitoring applications built on top of OPNX.Lib.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\OpnxPlaybackTimeline\OpnxPlaybackTimeline.Data.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="8.0.0.1" />
    <PackageReference Include="OPNX.Lib" Version="0.1.0-preview.20260410.2" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
  </ItemGroup>

</Project>
